// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_mainMenuScreen
void ui_mainMenuScreen_screen_init(void);
lv_obj_t * ui_mainMenuScreen;
void ui_event_settingsButton(lv_event_t * e);
lv_obj_t * ui_settingsButton;
lv_obj_t * ui_settingsButtonLabel;
void ui_event_ConfigureButton(lv_event_t * e);
lv_obj_t * ui_ConfigureButton;
lv_obj_t * ui_configureButtonLabel;
void ui_event_onButton(lv_event_t * e);
lv_obj_t * ui_onButton;
lv_obj_t * ui_onButtonLabel;
void ui_event_offButton(lv_event_t * e);
lv_obj_t * ui_offButton;
lv_obj_t * ui_offButtonLabel;


// SCREEN: ui_configureScreen
void ui_configureScreen_screen_init(void);
lv_obj_t * ui_configureScreen;
lv_obj_t * ui_networkTimePanel;
lv_obj_t * ui_networkTimeSwitch;
lv_obj_t * ui_networkTimeLabel;
lv_obj_t * ui_dimmerPanel;
lv_obj_t * ui_dimmerSwitch;
lv_obj_t * ui_dimmerLabel;
lv_obj_t * ui_colorPanel;
lv_obj_t * ui_colorLabel;
lv_obj_t * ui_redSlider;
lv_obj_t * ui_greenSlider;
lv_obj_t * ui_blueSlider;
void ui_event_configureBackButton(lv_event_t * e);
lv_obj_t * ui_configureBackButton;
lv_obj_t * ui_configureBackButtonLabel;


// SCREEN: ui_settingsScreen
void ui_settingsScreen_screen_init(void);
lv_obj_t * ui_settingsScreen;
void ui_event_settingsBackButton(lv_event_t * e);
lv_obj_t * ui_settingsBackButton;
lv_obj_t * ui_settingsBackButtonLabel;
lv_obj_t * ui_sendStatisticsPanel;
lv_obj_t * ui_sendStatisticsSwitch;
lv_obj_t * ui_sendStatisticsLabel;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_settingsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settingsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_settingsScreen_screen_init);
    }
}
void ui_event_ConfigureButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_configureScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_configureScreen_screen_init);
    }
}
void ui_event_onButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_offButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_onButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
}
void ui_event_offButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_offButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_onButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_configureBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainMenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_mainMenuScreen_screen_init);
    }
}
void ui_event_settingsBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainMenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_mainMenuScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_mainMenuScreen_screen_init();
    ui_configureScreen_screen_init();
    ui_settingsScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_mainMenuScreen);
}
