// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_mainMenuScreen_screen_init(void)
{
    ui_mainMenuScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainMenuScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settingsButton = lv_btn_create(ui_mainMenuScreen);
    lv_obj_set_width(ui_settingsButton, 125);
    lv_obj_set_height(ui_settingsButton, 32);
    lv_obj_set_x(ui_settingsButton, 0);
    lv_obj_set_y(ui_settingsButton, 50);
    lv_obj_set_align(ui_settingsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsButton, lv_color_hex(0x848484), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsButtonLabel = lv_label_create(ui_settingsButton);
    lv_obj_set_width(ui_settingsButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingsButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settingsButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settingsButtonLabel, "Settings");

    ui_ConfigureButton = lv_btn_create(ui_mainMenuScreen);
    lv_obj_set_width(ui_ConfigureButton, 125);
    lv_obj_set_height(ui_ConfigureButton, 32);
    lv_obj_set_x(ui_ConfigureButton, 0);
    lv_obj_set_y(ui_ConfigureButton, 13);
    lv_obj_set_align(ui_ConfigureButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigureButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfigureButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfigureButton, lv_color_hex(0x848484), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigureButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_configureButtonLabel = lv_label_create(ui_ConfigureButton);
    lv_obj_set_width(ui_configureButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_configureButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_configureButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_configureButtonLabel, "Configure");

    ui_onButton = lv_btn_create(ui_mainMenuScreen);
    lv_obj_set_width(ui_onButton, 60);
    lv_obj_set_height(ui_onButton, 32);
    lv_obj_set_x(ui_onButton, -32);
    lv_obj_set_y(ui_onButton, -25);
    lv_obj_set_align(ui_onButton, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_onButton, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_onButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_onButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_onButton, lv_color_hex(0x2FB617), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_onButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_onButtonLabel = lv_label_create(ui_onButton);
    lv_obj_set_width(ui_onButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_onButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_onButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_onButtonLabel, "ON");

    ui_offButton = lv_btn_create(ui_mainMenuScreen);
    lv_obj_set_width(ui_offButton, 60);
    lv_obj_set_height(ui_offButton, 32);
    lv_obj_set_x(ui_offButton, 33);
    lv_obj_set_y(ui_offButton, -25);
    lv_obj_set_align(ui_offButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_offButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_offButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_offButton, lv_color_hex(0xC81010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_offButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_offButtonLabel = lv_label_create(ui_offButton);
    lv_obj_set_width(ui_offButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_offButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_offButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_offButtonLabel, "OFF");

    lv_obj_add_event_cb(ui_settingsButton, ui_event_settingsButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConfigureButton, ui_event_ConfigureButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_onButton, ui_event_onButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_offButton, ui_event_offButton, LV_EVENT_ALL, NULL);

}
