// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
void ui_settingsScreen_screen_init(void)
{
    ui_settingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_settingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settingsBackButton = lv_btn_create(ui_settingsScreen);
    lv_obj_set_width(ui_settingsBackButton, 125);
    lv_obj_set_height(ui_settingsBackButton, 32);
    lv_obj_set_x(ui_settingsBackButton, 0);
    lv_obj_set_y(ui_settingsBackButton, lv_pct(33));
    lv_obj_set_align(ui_settingsBackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingsBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settingsBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsBackButton, lv_color_hex(0x848484), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsBackButtonLabel = lv_label_create(ui_settingsBackButton);
    lv_obj_set_width(ui_settingsBackButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingsBackButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settingsBackButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settingsBackButtonLabel, "Back");

    ui_sendStatisticsPanel = lv_obj_create(ui_settingsScreen);
    lv_obj_set_height(ui_sendStatisticsPanel, 35);
    lv_obj_set_width(ui_sendStatisticsPanel, lv_pct(90));
    lv_obj_set_x(ui_sendStatisticsPanel, 0);
    lv_obj_set_y(ui_sendStatisticsPanel, -47);
    lv_obj_set_align(ui_sendStatisticsPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sendStatisticsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sendStatisticsPanel, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sendStatisticsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sendStatisticsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_sendStatisticsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_sendStatisticsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_sendStatisticsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_sendStatisticsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sendStatisticsSwitch = lv_switch_create(ui_sendStatisticsPanel);
    lv_obj_set_width(ui_sendStatisticsSwitch, 45);
    lv_obj_set_height(ui_sendStatisticsSwitch, 20);
    lv_obj_set_y(ui_sendStatisticsSwitch, 0);
    lv_obj_set_x(ui_sendStatisticsSwitch, lv_pct(-45));
    lv_obj_set_align(ui_sendStatisticsSwitch, LV_ALIGN_CENTER);


    ui_sendStatisticsLabel = lv_label_create(ui_sendStatisticsPanel);
    lv_obj_set_width(ui_sendStatisticsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sendStatisticsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_sendStatisticsLabel, 0);
    lv_obj_set_x(ui_sendStatisticsLabel, lv_pct(7));
    lv_obj_set_align(ui_sendStatisticsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sendStatisticsLabel, "Share usage statistics");
    lv_obj_set_style_text_font(ui_sendStatisticsLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_settingsBackButton, ui_event_settingsBackButton, LV_EVENT_ALL, NULL);

}
